# Generated by Django 5.0.3 on 2024-03-24 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(null=True)),
                ('internal_code1', models.CharField(max_length=50, null=True)),
                ('internal_code2', models.CharField(max_length=50, null=True)),
                ('internal_code3', models.CharField(max_length=50, null=True)),
                ('serial_number', models.CharField(max_length=50, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('mac_address', models.CharField(max_length=50, null=True)),
                ('windows_license', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentalCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=50)),
                ('details', models.TextField(null=True)),
                ('sector', models.CharField(max_length=50)),
                ('rental_company', models.CharField(max_length=50)),
                ('internal_code1', models.CharField(max_length=50, null=True)),
                ('internal_code2', models.CharField(max_length=50, null=True)),
                ('internal_code3', models.CharField(max_length=50, null=True)),
                ('serial_number', models.CharField(max_length=50, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('mac_address', models.CharField(max_length=50, null=True)),
                ('windows_license', models.CharField(max_length=50, null=True)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tech_asset.asset')),
            ],
        ),
        migrations.CreateModel(
            name='AssetQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.TextField(null=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_tech_asset.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tech_asset.category'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='rental_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tech_asset.rentalcompany'),
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assets', models.ManyToManyField(to='app_tech_asset.asset')),
                ('sectors', models.ManyToManyField(to='app_tech_asset.sector')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tech_asset.sector'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_tech_asset.category')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tech_asset.subcategory'),
        ),
        migrations.CreateModel(
            name='SubSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('parent', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_tech_asset.sector')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='subsector',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_tech_asset.subsector'),
        ),
    ]
