# Generated by Django 5.0.6 on 2024-05-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech_asset', '0002_alter_asset_subcategory_alter_asset_subsector'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='internalcode01',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='internalcode02',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='internalcode03',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
