# Generated by Django 5.0.6 on 2024-06-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech_asset', '0003_globalsettings_internalcode01_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='name',
            field=models.CharField(default='Kit', max_length=50),
        ),
    ]
