# Generated by Django 5.0.6 on 2024-07-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech_asset', '0005_remove_kit_sectors_kit_sectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='kit',
            name='subsectors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_tech_asset.subsector'),
        ),
        migrations.CreateModel(
            name='KitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kit', max_length=50)),
                ('modification_type', models.CharField(max_length=50)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=50)),
                ('sector', models.CharField(max_length=50)),
                ('subsector', models.CharField(max_length=50)),
                ('assets', models.ManyToManyField(to='app_tech_asset.asset')),
                ('kit_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_tech_asset.kit')),
            ],
        ),
    ]
