# Generated by Django 5.0.6 on 2024-07-09 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech_asset', '0007_kit_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kithistory',
            name='kit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_tech_asset.kit'),
        ),
    ]
