# Generated by Django 5.0.6 on 2024-07-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech_asset', '0008_alter_kithistory_kit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='new_sector',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='new_subsector',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='previous_sector',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='previous_subsector',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
