# Generated by Django 5.0.6 on 2024-07-12 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tech_asset', '0010_remove_asset_new_sector_remove_asset_new_subsector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kithistory',
            name='new_sector',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kithistory',
            name='new_subsector',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kithistory',
            name='previous_sector',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='kithistory',
            name='previous_subsector',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tech_asset.category'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='rental_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tech_asset.rentalcompany'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tech_asset.sector'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tech_asset.subcategory'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='subsector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tech_asset.subsector'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='sectors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tech_asset.sector'),
        ),
        migrations.AlterField(
            model_name='kit',
            name='subsectors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_tech_asset.subsector'),
        ),
    ]
